config/routes.rb
Classy::Application.routes.draw do
  
  devise_for :users
  resources :users
  
  resources :topics do
    resources :feeds
  end
  
  root 'topics#index'

  

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  validates :text, presence: true, length: { maximum: 200 }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :feeds, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
   has_many :feeds

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :first_name
      devise_parameter_sanitizer.for(:sign_up) << :last_name
    end
    
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  
  before_action :authenticate_user!
  
   def create
      @topic = Topic.find(params[:topic_id])
      @feed = @topic.feeds.create(params[:feed].permit(:feeder, :text))
      @feed.user = current_user
      @feed.save

      respond_to do |format|
        format.js 
        format.html { 
          redirect_to topic_path(@topic) 
        }
      end
    end

    def destroy
      @topic = Topic.find(params[:topic_id])
      @feed = @topic.feeds.find(params[:id])
      @feed.destroy

      respond_to do |format|
        format.js
        format.html { 
          redirect_to topic_path(@topic)
        }
      end
    end

  end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

    before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

    def new
      @topic = Topic.new
    end

    def create
      @topic = Topic.new( topic_params )
      @topic.user = current_user
      if @topic.save
        redirect_to @topic
      else
        render 'new'
      end
    end

    def update
      @topic = Topic.find( params[:id] )
      if @topic.update_attributes( topic_params )
        redirect_to @topic
      else
        render 'edit'
      end
    end

    def edit
      @topic = Topic.find( params[:id] )
    end

    def destroy
      @topic = Topic.find( params[:id] )
      @topic.destroy
      redirect_to topics_path
    end

    def index
      @topics = Topic.order( 'created_at DESC' ).limit( @topics_per_page )

    end

    def show
      @topic = Topic.find( params[:id] )

    end

    private
      def topic_params
        params.require(:topic).permit( :title, :description )
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
  MONTH_NAMES = ['-','Jan.','Feb.','March','April','May','June','July','Aug.','Sept.','Oct.','Nov.','Dec.']  
  
  def nice_date(dt)
    return '-' if dt.nil?
    mi = ' p.m.'
    mi = ' a.m.' if dt.strftime("%p") == 'AM'
    time_str = dt.strftime("%l:%M") + mi
    if time_str == '12:00 p.m.'
      time_str = 'noon'
    elsif time_str == '12:00 a.m.'
      time_str = 'midnight'
    end
    format_str = "%A, " + MONTH_NAMES[dt.month()] + " %d, %Y, " + time_str
    dt.strftime(format_str)
  end
  
  def nice_short_date(dt)
    return '-' if dt.nil?
    format_str = MONTH_NAMES[dt.month()] + " %-d, %Y"
    dt.strftime(format_str)
  end
  
  def title( page_title )
    content_for :title, page_title.to_s
  end

end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_collapse.html.erb
<% @topics.each do |s| -%>		
<table>		

			 <div class="topicBox">

			 <div class="accordion-group">  
              <div class="accordion-heading">  
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
						<tr>
							<td><div class="topicRow">
							<%= s.title %> 
							</div>
							</td>
						</tr>

					</div>
					</table>

				<div id="collapseThree" class="accordion-body collapse">  
	                <div class="accordion-inner">  
					<div class="feedBox">  
	                 	<%= s.text %>

	                </div>  
	              </div>  
	            </div>
<% end %>

<script type="text/javascript" src="/twitter-bootstrap/twitter-bootstrap-v2/docs/assets/js/jquery.js"></script>  
<script type="text/javascript" src="/twitter-bootstrap/twitter-bootstrap-v2/docs/assets/js/bootstrap-collapse.js"></script>  

app/views/feeds/_feed.html.erb
<blockquote>
  	<p><%= feed.text %></p>
	<small><%= feed.user.email %>
	  <% if user_signed_in? and current_user.id == feed.user.id %>
				<%= link_to "Delete", topic_path(feed), method: :delete, data: { confirm: 'Are you sure you want to delete the topic?'} %>
		<% end %>
</blockquote>

app/views/feeds/_form.erb
<%= form_for( [@topic, @topic.feeds.build], html: { role: 'form' }, remote: true ) do |f| %>

	<div class="form-group">
    	<%= f.text_area :text, class: 'form-control' %>
	</div>
	<div class="form-group">
    	<%= f.submit class: 'btn' %>
	</div>
	
<% end %>

app/views/feeds/create.js.erb
$("#feeds-list").html("<%= escape_javascript( render @topic.feeds ) %>" );
$("#feeds-form").html("<%= escape_javascript( render 'feeds/form' ) %>" );

app/views/feeds/destroy.js.erb
$("#feeds-list").html("<%= escape_javascript( render @topic.feeds ) %>" );

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EC</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<%= yield %>
</body>
</html>

app/views/topics/_form.html.erb
<%= form_for( @topic ) do |f| %>

<% if @topic.errors.any? %>
<div>
	<h2><%= pluralize( @topic.errors.count, "error" ) %> prohibited this topic from being saved.</h2>
	<ul>
		<% @topic.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-group">
	<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.label :description %>
	<%= f.text_area :description, class: 'form-control', rows: '12' %>
</div>

<div class="form-group">
	<%= f.submit class: 'btn btn-primary' %>
</div>
	

<% end %>

app/views/topics/_topic.html.erb
<article>
	<h2><%= link_to topic.title, topic_path(topic) %></h2>
	<p><%= "Description: " + topic.description %></p>
	<p>
		Posted: <%= nice_short_date( topic.created_at ) %>
		<br>
	</p>
	<p>
	  <h4>Comments </h4>
	<% topic.feeds.each do |feed| %>
		<%= topic.user.first_name %> :
		<%= feed.text %><br>
	<% end %>
	</p>
</article>

<hr>

app/views/topics/edit.html.erb
<%= title( 'Edit Topic' ) %>

<div class="row-fluid" >
	<div class="col-md-12">
		
		<h1>Edit Topic</h1>

		<%= render 'form' %>

	</div>
</div>

app/views/topics/index.html.erb
<div class = 'container'>
<div >
	<% if user_signed_in? %>
    <%= current_user.email %>
    <br>
      <%= link_to( "Sign out", destroy_user_session_path, method: :delete ) %>
      <br>
			<%= link_to 'New Feed', new_topic_path%>
		
	<% else %>
		<li><%= link_to( "Sign in", new_user_session_path ) %></li>
	<% end %>
</div>


<h1>News Feed</h1>
<br>
<%= render @topics %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path, class: 'btn btn-default' %>

app/views/topics/show.html.erb
<%= title( @topic.title ) %>
<%= link_to 'Back to Feed Index', topics_path %>

		<h2>
			<%= @topic.title %>
		</h2>
		<p>
			<%= @topic.description %>
		</p>
		<p>
			By <%= @topic.user.email %>, Posted <%= nice_short_date( @topic.created_at ) %>

	    <% if user_signed_in? and current_user.id == @topic.user.id %>
  				<%= link_to 'Edit', edit_topic_path(@topic) %> or
  				<%= link_to "Delete", topic_path(@topic), method: :delete, data: { confirm: 'Are you sure you want to delete the topic?'} %>
  		<% end %>
        </p>

		<h4>Comments</h4>
		<div id="feeds-list">
			<%= render @topic.feeds %>
		</div>

		<% if user_signed_in? %>
			<h4>Add Comments<h4>
			<div id="feeds-form">
				<%= render "feeds/form" %>
			</div>
		<% end %>
 
		
	</div>
</div>